# -*- coding: utf-8 -*-
"""Stock data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kjDCryWrwpKX_ttelbN1G7YYjsGQM3Ng
"""

import pandas as pd
import yfinance as yf

# Get the ticker symbols for the top 20 stocks from Yahoo Finance
symbols = ['MSFT', 'AAPL', 'NVDA', 'AMZN', 'META', 'GOOGL', 'BRK-B', 'LLY',
           'AVGO', 'JPM', 'TSLA', 'UNH', 'V', 'XOM', 'JNJ', 'MA', 'PG', 'HD',
           'AMD', 'COST']
symbol_names = [yf.Ticker(symbol).info['longName'] for symbol in symbols]

# Get the monthly data for the last 100 months
df = yf.download(tickers=symbols, period='100mo', interval='1mo', group_by='ticker')

f = open("ticker_cmds.txt", "w")
for i, (symbol, symbol_name) in enumerate(zip(symbols, symbol_names)):
    data = df.loc[:, (symbol, ['Close', 'Open', 'High', 'Low'])]
    # Extract data
    close_price = list(map(int, data[symbol]['Close'].tolist()))
    open_price = list(map(int, data[symbol]['Open'].tolist()))
    high_price = list(map(int, data[symbol]['High'].tolist()))
    low_price = list(map(int, data[symbol]['Low'].tolist()))

    # Transform data into C code
    cmd = (f'ticker.stocks[{i}] = (stock_t){{\n'
          f'    .name = "{symbol_name}", \n'
          f'    .symbol = "{symbol}", \n'
          f'    .open_price = {{ {",".join([str(e) for e in open_price])} }}, \n'
          f'    .close_price = {{ {",".join([str(e) for e in close_price])} }} \n'
          f'}}; \n\n'
          )
    f.write(cmd)
f.close()

# Generate News
news_ind = 22;
headlines = [
    "Amazon receives 238 proposals for its second headquarters",
    "Kobe Steel faked product data for over 10 years, sending shockwaves",
    "Alphabet's Google uncovers Russia-backed ads on YouTube, Gmail",
    "Tesla fires hundreds of workers as company struggles with production",
    "Airbus to acquire majority stake in Bombardier C Series program",
    "AT&T's $85 billion acquisition of Time Warner hit with lawsuit",
    "CVS Health to acquire health insurer Aetna for $69 billion",
    "Intel products hit with security flaw in widespread 'KRACK' attack",
    "Bitcoin soars above $6,000, doubling in price in less than a month",
    "Disney extends buyout negotiations after hitting a 'slew of issues'"
]
for i in range(10):
    cmd = f'    news[{news_ind}][{i}] = "{headlines[i]}";'
    print(cmd)
