# -*- coding: utf-8 -*-
"""Stock data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kjDCryWrwpKX_ttelbN1G7YYjsGQM3Ng
"""

import pandas as pd
import yfinance as yf

# Get the ticker symbols for the top 20 stocks from Yahoo Finance
symbols = ['MSFT', 'AAPL', 'NVDA', 'AMZN', 'META', 'GOOGL', 'BRK-B', 'LLY',
           'AVGO', 'JPM', 'TSLA', 'UNH', 'V', 'XOM', 'JNJ', 'MA', 'PG', 'HD',
           'AMD', 'COST']
symbol_names = [yf.Ticker(symbol).info['longName'] for symbol in symbols]

# Get the monthly data for the last 100 months
df = yf.download(tickers=symbols, period='100mo', interval='1mo', group_by='ticker')

f = open("ticker_cmds.txt", "w")
for i, (symbol, symbol_name) in enumerate(zip(symbols, symbol_names)):
    data = df.loc[:, (symbol, ['Close', 'Open', 'High', 'Low'])]
    # Extract data
    close_price = list(map(int, data[symbol]['Close'].tolist()))
    open_price = list(map(int, data[symbol]['Open'].tolist()))
    high_price = list(map(int, data[symbol]['High'].tolist()))
    low_price = list(map(int, data[symbol]['Low'].tolist()))

    # Transform data into C code
    cmd = (f'ticker.stocks[{i}] = (stock_t){{\n'
          f'    .name = "{symbol_name}", \n'
          f'    .symbol = "{symbol}", \n'
          f'    .open_price = {{ {",".join([str(e) for e in open_price])} }}, \n'
          f'    .close_price = {{ {",".join([str(e) for e in close_price])} }} \n'
          f'}}; \n\n'
          )
    f.write(cmd)
f.close()

